name: Med-Portal Paper
description: Compile and generate Paper metadata
inputs:
  issue_id:
    description: The review issue id for the paper
    required: true
  repository_url:
    description: The repository URL of the submission containing the paper file
    required: true
  branch:
    description: Git branch where the paper is located
    required: false
    default: ""
outputs:
  pdf_path:
    description: "Path to the generated PDF file"
    value: ${{ steps.compilation-result.outputs.paper_pdf_path }}
  paper_file_path:
    description: "Path to the paper's .md/.tex source file"
    value: ${{ steps.paper-finder.outputs.paper_file_path }}
runs:
  using: "composite"
  steps:
    - name: Install Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.2.2
        bundler-cache: true
        cache-version: paper-files
        bundler: Gemfile.lock
        working-directory: ${{ github.action_path }}
    - name: Find paper file
      id: paper-finder
      shell: bash
      env:
        REPO_URL: ${{ inputs.repository_url }}
        PAPER_BRANCH: ${{ inputs.branch }}
        BUNDLE_GEMFILE: ${{ github.action_path }}/Gemfile
      run: |
        bundle exec ruby ${{ github.action_path }}/get_paper.rb
    - name: Build paper artifacts
      id: build-paper
      uses: ACCESS-NRI/med-make-recipe-action@main
      with:
        paper-path: ${{ steps.paper-finder.outputs.paper_file_path }}
    - name: Check results
      id: compilation-result
      shell: bash
      run: |
        ruby ${{ github.action_path }}/check_result.rb ${{ steps.paper-finder.outputs.paper_file_path }} pdf

branding:
  icon: file-text
  color: blue
